FROM umlbuild AS build

FROM fedora:latest

RUN dnf -y update
RUN dnf clean all

COPY --from=build /src /src
COPY --from=build /app /app
COPY --from=build /lib/modules /lib/modules

ADD --chmod=755 bin/* /app/bin/
ADD etc /app/etc

CMD /app/bin/container-init
