FROM kernelsrc AS kinstall

ADD src /src
WORKDIR /src
RUN mkdir -p /app/bin
RUN gcc -o /app/bin/halt halt.c
RUN mkdir -p /usr/src
WORKDIR /usr/src
RUN tar xf /src/linux-*.tar.xz
RUN mv linux-* linux
WORKDIR /usr/src/linux

ADD midiuml.config .
RUN make ARCH=um allnoconfig KCONFIG_ALLCONFIG=midiuml.config
RUN make ARCH=um prepare modules_prepare

RUN make -j4 linux ARCH=um
RUN make -j4 modules ARCH=um

RUN make modules_install INSTALL_MOD_PATH=/ ARCH=um
RUN mkdir -p /app
RUN mkdir -p /app/bin
RUN cp linux /app/bin/linux
WORKDIR /

FROM fedorakernelbuild
COPY --from=kinstall /app/bin/halt /app/bin/halt
COPY --from=kinstall /app/bin/linux /app/bin/linux
COPY --from=kinstall /lib/modules /lib/modules
COPY --from=kinstall /usr/src /usr/src
COPY --from=kinstall /src /src

WORKDIR /
